// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-uPXAV2xZdwMHzTjiIZTeO2tLKMwVVOk',
    appId: '1:180634287254:web:f80a76d9effdc6b8aa56b7',
    messagingSenderId: '180634287254',
    projectId: 'mhapp-bbd3f',
    authDomain: 'mhapp-bbd3f.firebaseapp.com',
    storageBucket: 'mhapp-bbd3f.appspot.com',
    measurementId: 'G-SXQE24B72N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoS5z8c_s4ycUDxorZCzXQQMSHQxmHmKU',
    appId: '1:180634287254:android:d9f6a7269ebcd12aaa56b7',
    messagingSenderId: '180634287254',
    projectId: 'mhapp-bbd3f',
    storageBucket: 'mhapp-bbd3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-yiHKB_QrWn0Pt0RYoWaDdgNClAC_mtc',
    appId: '1:180634287254:ios:39ed36a9cd53c7f4aa56b7',
    messagingSenderId: '180634287254',
    projectId: 'mhapp-bbd3f',
    storageBucket: 'mhapp-bbd3f.appspot.com',
    iosBundleId: 'com.example.mhapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-yiHKB_QrWn0Pt0RYoWaDdgNClAC_mtc',
    appId: '1:180634287254:ios:c82825da8237df17aa56b7',
    messagingSenderId: '180634287254',
    projectId: 'mhapp-bbd3f',
    storageBucket: 'mhapp-bbd3f.appspot.com',
    iosBundleId: 'com.example.mhapp.RunnerTests',
  );
}
